#!/bin/bash

if [ -z "$(ls -a $HOME | grep ".PLTFilter")" ]; then
    mkdir $HOME/.PLTFilter
fi

chmod +x all_params get_data goat pltfilter
cp all_params get_data goat pltfilter $HOME/.PLTFilter

if [ -z "$(cat $HOME/.bashrc | grep "PATH+=:$HOME/.PLTFilter")" ]; then
    echo -e "\n## PLTFilter path\nPATH+=:$HOME/.PLTFilter" >> $HOME/.bashrc
    PATH+=:$HOME/.PLTFilter
fi
